### ISSUE TITLE
Form autofill

### ISSUE THREAD

**Issue by jonathanKingston** [marcoscaceres/web-payments-proto#20]
Will form autofill options be available from existing address data etc?

As this is privileged interface there shouldn't be a risk in autofilling if there is only one too. Again as previously mentioned it could advance to the next step in the flow if all the data is filled out (clicks cost money).

**Comment by marcoscaceres** [comment]
> Will form autofill options be available from existing address data etc?

Yep. Absolutely! 

> As this is privileged interface there shouldn't be a risk in autofilling if there is only one too. Again as previously mentioned it could advance to the next step in the flow if all the data is filled out (clicks cost money).

Exactly. If you check the prototype, you can see it integrates beautifully:

https://marcoscaceres.github.io/web-payments-proto/
